### ISSUE TITLE
Allow support for enabling GDKP if Master Loot is not enabled or user isn't the Loot Master

### ISSUE THREAD

**Issue by SapQT** [Gogo1951/GDKPd-Classic#11]
Many guilds that use this in house and have players using pass on loot and the person collecting loot just rolling need on things removes the need for someone to manually run over and loot the boss. Would like to see an option where that person can start auctions without having to enable master loot and giving master loot to that person.

**Comment by Gogo1951** [comment]
The reason this isn't enabled is that it would lead to a situation where more than 1 person could run auctions. And that'd be a potential mess. Or the add-on would have to talk to other users with the add-on and establish who was the auctioneer. It's a good idea, but it's not a simple thing to fix with the current code base. Flag this again in the future once the add-on gets rebuilt.
