### ISSUE TITLE
GDKPd Options Interface - Auctioneer

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GDKPd-Classic#26]
# Story

# Acceptance Criteria

* Default Auction time is 20 seconds.
* Announce on 5-second Intervals, default. Good if we keep this consistent for everyone, we want people to be able to join any GDKP and have it work the same way.
* Once a bid happens, if you have less than 10 second left, the clock goes back up to 10 seconds. All bids, even failed bids, set the timer to 10 seconds left.

# Wireframes / Design Links

![image](https://user-images.githubusercontent.com/55365231/204104134-11363bef-f675-49ae-9131-7def3e97dfd8.png)

# Legacy Screenshots

**Comment by TannerShmoog** [comment]
Hide buttom checkbox for now

**Comment by Gogo1951** [comment]
We can leave this out for now.

![image](https://user-images.githubusercontent.com/55365231/204102825-d30427c3-3074-4c38-9e6e-faa0a2846604.png)
