### ISSUE TITLE
Auction Session History Viewer

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GDKPd-Classic#31]
# Story

Need a way to see past raids, and export data about what dropped, what it sold for, and who bought it.

# Acceptance Criteria

* May be useful to have an "average item sold for" data.
* May be useful to know who the "whales" are so you can track your big spenders over time.
* Data Export : Loot Lists
* Data Export : Buyers

# Wireframes / Design Links

# Legacy Screenshots

**Comment by TannerShmoog** [comment]
less detailed dupe of #38
