### ISSUE TITLE
commas are ignored on bids

### ISSUE THREAD

**Issue by SaffatHasan** [Gogo1951/GDKPd-Classic#36]
![image](https://user-images.githubusercontent.com/18339668/202599462-ff2bef16-d5ba-4aca-991b-0e5582e736f8.png)

1,5k is recorded as a 5k bid rather than 1.5k

**Comment by Gogo1951** [comment]
Hey @SaffatHasan ,

Thanks mate. We're not making any updates to the legacy code at this time. Full speed ahead on the re-write. Cheers!
